#!/bin/sh
# Implement a logging function for Dotkit.  If Dotkit finds an executable
# file at $DK_ROOT/etc/log, it assumes this file is a logging program,
# and executes it.
# Arguments passed to this script are as follows:
# $1: _dk_self, the full pathname to the Dotkit just read.
# $2: _dk_op, the current Dotkit operation - use or unuse.

PATH=/usr/bin:/bin
export PATH

# Define some information you want to log.
info=`date "+%F-%T"`"|$1|$2|$_dk_shell"

# Make sure the logger exec is around
if [ -x /bin/logger ]; then
  # Log info to message log.
  /bin/logger -t dotkit "$info"
fi


