# A basic .cshrc for use with Dotkit for csh and tcsh.
# Used for both .cshrc and .login.  (I.e., there is no .login file.)

# Optional: Before you initialize Dotkit, set DK_NODE to reference any
# project or group specific dotkits that you want to catalog.
#setenv DK_NODE /my/special/dotkits

# Look for Dotkit first in $DK_ROOT, then $HOME, then LLNL default.
if ( $?DK_ROOT ) then
  eval `$DK_ROOT/init`
else if ( -d "$HOME/dotkit" ) then
  eval `$HOME/dotkit/init`
else if ( -d "/usr/gapps/dotkit" ) then
  eval `/usr/gapps/dotkit/init`
endif

# This conditional needs to execute once only.
if ( ! $?SETUP_ONCE ) then
  setenv SETUP_ONCE 1
  use -q Sys Dev Prefs
endif

# Remainder is read by every shell instance.
use -q alia1++ myalia++
