#!/bin/sh
#
# Control the iRODS servers.
#
# Usage is:
#	irodsctl [options]
#
# Type 'irodsctl --help' for a list of options.
#
# This shell script runs the 'irodsctl' Perl script.
#
IRODS_HOME="/opt/iRODS"

if [ "$IRODS_HOME" = "" ]; then
	# Try using the current directory
	IRODS_HOME=`pwd`
	if [ ! -f $IRODS_HOME/scripts ]; then
		echo "Please run 'irodssetup' first to configure and build iRODS."
		exit 1
	fi
fi

KRB5_KTNAME=$IRODS_HOME/server/config/krb5.keytab
export KRB5_KTNAME

TNS_ADMIN=$IRODS_HOME/server/config
export TNS_ADMIN

# allow daemons to make core files
ulimit -c unlimited

# logging: 3 is only error, 5 is notice, 7 is debug, 8 is more debug
spLogLevel=5
export spLogLevel

# log the SQL statements being sent to the DB
#spLogSql=1
#export spLogSql

# use this file to provide iRODS environment variables
# for the services. Need it here so that we can have
# different settings between dev and prod
irodsEnvFile=/opt/iRODS/config/.irodsEnv
export irodsEnvFile

# use this user as the effective user in the server processes
irodsServiceUser=irods
export irodsServiceUser

$IRODS_HOME/scripts/runperl --dir $IRODS_HOME --script $IRODS_HOME/scripts/perl/irodsctl.pl $*
ExitCode="$?"
exit $ExitCode

