#!/bin/sh
# Usage:
#   ARCH_TYPE=`/path/to/archtype`          in sh, ksh, zsh, bash
#   setenv ARCH_TYPE `/path/to/archtype`   in csh, tcsh

PATH=/bin:/usr/bin:/usr/sbin:/sbin
export PATH

if [ -r /etc/home.config ]; then
  ARCH_TYPE=`grep ARCH_TYPE /etc/home.config | cut -d" " -f2`
  echo $ARCH_TYPE
  exit
fi

VENDOR=`grep vendor /proc/cpuinfo | tail -1 | awk '{print $3}'`

ARCH_TYPE=unknown

case "$VENDOR" in
  GenuineIntel*)
    ARCH_TYPE=intel
    ;;
  AuthenticAMD*) 
    ARCH_TYPE=amd
    ;;
  *) echo "ARCH_TYPE: CPU arch type unknown: ${VENDOR}" >&2 ;;
esac

echo $ARCH_TYPE
test "$ARCH_TYPE" != "unknown"
exit

