#!/usr/bin/expect

set host [lindex $argv 0]
set passw [lindex $argv 1]
set enpassw [lindex $argv 2]
set user [lindex $argv 3]
set ip [lindex $argv 4]
set date [exec date +%Y%m%d]

spawn telnet "$host"
expect "User:"
send "$user\r"
expect "Password:"
send "$passw\r"
expect "$host>"
send "enable\r"
expect "$host#"
send "copy running-config tftp://$ip/$date/$host\r"
expect "start?"
send "y\r"
expect "$host#"
send "quit\r"
expect EOF
exit 0

