#!/usr/bin/expect

set host [lindex $argv 0]
set passw [lindex $argv 1]
set enpassw [lindex $argv 2]
set user [lindex $argv 3]
set ip [lindex $argv 4]
set date [exec date +%Y%m%d]

spawn ssh -1 "$user@$host"
expect "password:"
send "$passw\r"
expect "$host#"
send "copy running-config tftp\r"
expect "IP address"
send "$ip\r"
expect "file name"
send "$date/$host\r"
expect "$host#"
send "exit\r"
expect eof
exit 0
