<input
    data-editor="true"
    data-editor-class="TimeEdit"
    data-field-name="{$Editor->GetFieldName()}"
    data-editable="true"
    id="{$Editor->GetName()}"
    name="{$Editor->GetName()}"
    value="{$Editor->GetValue()}"
    timeedit="true"
    {$Validators.InputAttributes}
>