#!/bin/sh

# Here we define Usage -- define once, print many
USAGE="Usage: `basename $0` \$NODE"

#HOST is the only ARG
HOST=$1

# Here we define how many arguments we should accept
ARG_NO=1

# error codes as defined in /usr/include/sysexits.h
E_OK=0       		# successful termination
E_USAGE=64      	# command line usage error 
E_NOINPUT=66      	# cannot open input
E_NOHOST=68		# host not found
E_UNAVAILABLE=69 	# service unavailable

# Here we test the number of arguments
if [ $# -ne "$ARG_NO" ]; then
        echo 1>&2 $USAGE
        exit $E_USAGE
fi

function IBM {
	tabdump mp | tr -d '"' | grep -w $HOST | awk -F, '{print "node: "$1 "\nchassis: "$2 "\nslot: "$3}'
}

function Dell {
	RESULT=$(tabdump nodepos | tr -d '"' | grep -w $HOST | awk -F, '{print "node: "$1 "\nchassis: "$3 "\nslot: "$4}')
	if [ -z "$RESULT" ] ; then
		echo "Host not found: Perhaps missing OMSA or really sick?" && exit $E_NOHOST
	else
		echo "$RESULT"
	fi	
}

VENDOR=$(tabdump nodelist | awk -F\" -v host=$HOST '$2 ~ host {print $4}')

if [[ $VENDOR == *ibm* ]]; then
	IBM
elif [[ $VENDOR == *dell* ]]; then
	Dell
else
	echo "Vendor not configured" && exit $E_UNAVALABLE
fi

exit $E_OK
