#!/bin/bash

OLDNAME=$1
NEWNAME=$2
TABLES=$(tabgrep $OLDNAME)

#for TABLE in $TABLES; do
#	echo "$TABLE"
#	nodech $OLDNAME $TABLE.node=$NEWNAME 2> /dev/null
#	noderm $OLDNAME 2> /dev/null
#done

IP=$(tabdump hosts | grep $OLDNAME| cut -f2 -d, | tr -d '"')
MAC=$(tabdump mac | grep $OLDNAME | cut -f3 -d, | tr -d '"')
TYPE=$(tabdump nodelist | grep $OLDNAME | cut -f4 -d\")

noderm $OLDNAME
svnbuild nodeadd $NEWNAME groups=$TYPE mac.interface=eth0 mac.mac=$MAC hosts.ip=$IP
