#!/bin/sh

#
# $Id$
#

# Uncomment the next line for testing
#set -x

#########################################################
#
# locate a node
# for example: nodelocate node1000
# 
#########################################################

PATH=/opt/xcat/bin:/opt/xcat/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/util/bin:/util/sbin:/usr/local/bin

# Here we define Usage -- define once, print many
USAGE="Usage: `basename $0` $NODE"

# Here we define how many arguments we should accept
ARG_NO=1

# error codes as defined in /usr/include/sysexits.h
E_OK=0       # successful termination
E_USAGE=64      # command line usage error 
E_NOINPUT=66      # cannot open input

# Here we test the number of arguments
if [ $# -ne "$ARG_NO" ]; then
        echo 1>&2 $USAGE
        exit $E_USAGE
fi

# switches
NODENUM=$1

#ok, we assume nobody futzed around with the files and won't check for existence

case $NODENUM in
        -help|--help|-h) echo 1>&2 $USAGE;;
        *) tabdump mp | tr -d '"' | grep -w $NODENUM | awk -F, '{print "node: "$1 "\nchassis: "$2 "\nslot: "$3}';;
esac



exit $E_OK
