#!/bin/bash
 
. /broad/tools/scripts/useuse

reuse -q Subversion-1.6

if [ $# -eq 1 ]; then
	echo "Please do not wrap your command in quotation marks."
	exit 1
elif [ $# -eq 0 ]; then
	echo "Please provide command to add node.  Otherwise, why are you running me?"
	exit 1
fi

if [ $1 != 'nodeadd' ]; then
	echo "This application is for nodeadd-ing only.  Please refrain from improper use."
	exit 1
fi

DIR=/root/subversion/xcat2/tables

$*

for TABLE in `tabdump`
do
tabdump $TABLE > $DIR/$TABLE.csv
done

rm $DIR/passwd.csv

COMMENT="Added $2"

cd $DIR
svn ci -m "$COMMENT" *
