#!/bin/bash

sudo foo 2>/dev/null
/broad/tools/scripts/s Python-2.6 /broad/tools/scripts/xcat2/update.py

/opt/xcat/sbin/makehosts -n 1>/dev/null
/opt/xcat/sbin/makedns -n 1>/dev/null
sudo /sbin/service named restart 1>/dev/null
sudo /sbin/service dhcpd stop 1>/dev/null
sudo rm -f /etc/dhcpd.conf 1>/dev/null
/opt/xcat/sbin/makedhcp -a -d 1>/dev/null
/opt/xcat/sbin/makedhcp -n 1>/dev/null
/opt/xcat/sbin/makedhcp -a 1>/dev/null
sudo /sbin/service dhcpd restart 1>/dev/null
