#!/bin/bash

LOCAL_MHL="/broad/tools/scripts/xcat2/build.host.listing"
if [ -f $LOCAL_MHL ]; then
	MHL_ENTRIES=$(diff -y --suppress-common-lines <(awk '$1 ~ /#xCAT#/ {print $2}' /sysman/install/broad/master.host.listing) $LOCAL_MHL)
         if [ -n "${MHL_ENTRIES:+x}" ]; then
		echo -e "The following records are being changed:\n"
		for ENTRY in "$MHL_ENTRIES"; do
		    echo -e "\t$ENTRY\n"
		done
        else
                echo "Records are up to date."
                exit 1
        fi

        echo "Confirm Changes [y/n]"
        until [[ ($confirmRes == "y") || ($confirmRes == "n") ]]; do
            read confirmRes
        done

        if [[ $confirmRes == "n" ]]; then
            exit 1
        fi

	for ENTRY in "$MHL_ENTRIES"; do
		HOST=$(echo "$ENTRY" | cut -f3 -d\|)
		NODEGROUPS=$(echo "$ENTRY" | cut -f4 -d\|)
		IP=$(echo "$ENTRY" | cut -f1 -d\|)
		MAC=$(echo "$ENTRY" | cut -f2 -d\|)

		if [[ $(nodels $HOST 2>/dev/null | wc -l) -eq 1 ]]; then
			noderm $HOST
                fi
        
		if [[ ($(echo "$ENTRY" | grep -c \<) -eq 1) || ($(echo "$ENTRY" | awk -F\| '{print NF}' | head -n 1) -gt 7) ]]; then
			if [[ $(nodels $HOST 2>/dev/null | wc -l) -eq 0 ]]; then
			    nodeadd $HOST groups=$NODEGROUPS hosts.ip=$IP mac.mac=$MAC
			else
                            echo "Possible duplicate entries for $HOST. Please fix."
                            exit 1
			fi
		fi
	done
elif [ ! -f $LOCAL_MHL ]; then
	noderm all
	MHL_ENTRIES=$(awk '$1 ~ /#xCAT#/ {print $2}' /sysman/install/broad/master.host.listing)
	HOSTS=$(echo "$MHL_ENTRIES" | awk -F\| '{print $3}')
	FILE_DIR=/tmp/updateTables
	HOST_FILE=$FILE_DIR/hosts.csv
	MAC_FILE=$FILE_DIR/mac.csv
	NODELIST_FILE=$FILE_DIR/nodelist.csv
	IPMI_FILE=$FILE_DIR/ipmi.csv
	MP_FILE=$FILE_DIR/mp.csv

	mkdir $FILE_DIR

	##Write Required Lines##
	echo "#node,ip,hostnames,otherinterfaces,comments,disable" > $HOST_FILE
	echo -e "#node,interface,mac,comments,disable\n\"all\",\"eth0\",,," > $MAC_FILE
	echo "#node,groups,status,statustime,appstatus,appstatustime,primarysn,comments,disable" > $NODELIST_FILE
	echo -e "#node,bmc,bmcport,username,password,comments,disable\n\"dell\",\"/\z/-rac/\",,,,," > $IPMI_FILE
	echo "#node,mpa,id,comments,disable" > $MP_FILE

	for HOST in $HOSTS; do
		GROUP=$(echo "$MHL_ENTRIES" | grep -w $HOST | awk -v host=$HOST -F\| '$3 ~ host {print $4}')
		MAC=$(echo "$MHL_ENTRIES" | grep -w $HOST | awk -v host=$HOST -F\| '$3 ~ host {print $2}' | tr '[:upper:]' '[:lower:]')
		IP=$(echo "$MHL_ENTRIES" | grep -w $HOST | awk -v host=$HOST -F\| '$3 ~ host {print $1}')
		CHASSIS=$(echo "$MHL_ENTRIES" | grep -w $HOST | awk -v host=$HOST -F\| '$3 ~ host {print $5}')
		SLOT=$(echo "$MHL_ENTRIES" | grep -w $HOST | awk -v host=$HOST -F\| '$3 ~ host {print $6}')

		if [[ -z $CHASSIS ]]; then
			echo "$HOST,$IP,,,," >> $HOST_FILE
			echo "$HOST,,$MAC,," >> $MAC_FILE
			echo "$HOST,\"$GROUP\"" >> $NODELIST_FILE
		else
			echo "$HOST,$IP,,,," >> $HOST_FILE
			echo "$HOST,,$MAC,," >> $MAC_FILE
			echo "$HOST,\"$GROUP\"" >> $NODELIST_FILE
			echo "$HOST,$CHASSIS,$SLOT,," >> $MP_FILE
		fi
	done

	for FILE in $(ls $FILE_DIR); do
		tabrestore $FILE_DIR/$FILE
	done
	rm -rf $FILE_DIR
fi

/broad/tools/scripts/xcat2/scrubDHCP.sh
