#!/bin/sh

OIFS=$IFS
IFS=','
NODE_LIST=$NODES
for NODE in $NODE_LIST
do
	echo "
		xCAT build from xcat2
		 $NODE install
		at $(date)" | mail -s "xCAT build from xCAT2  -- $NODE install ($(date +%F | tr -d '-'))" xcat@broadinstitute.org
done

IFS=$OIFS
