#!/bin/ksh -p

[[ $# != 1 ]] && { exit; }
export PATH=$HOME/scripts:$HOME/$SYS_TYPE/bin:/bin:/usr/bin:/usr/bin/X11

./dobuild1 $1

# Start up ghostview on the Postscript; capture its PID for later use.
gv ${1%.dot}.ps &
gv=$!

# Rerun roff when the source file changes; tickle ghostview
atchange $1 "./dobuild1 $1 && kill -HUP $gv" &
at=$!

# And wait here until ghostview exits
wait $gv

# kill atchange
kill $at
