#!/usr/bin/python

import os,sys

# we could use rrdtool directly instead of going through mrtg....
#import rrdtool

for filesys in sys.argv[1:]:
    fsinfo = os.statvfs(filesys)
    k_per_block = fsinfo.f_bsize / 1024
    #print filesys, fsinfo.f_blocks * k_per_block, fsinfo.f_bavail * k_per_block
    # MRTG expects the following set of lines, but later ones are optional
    #   incomingbytes
    #   outgoingbytes
    #   uptime of target
    #   name of target
    # so here we go...
    # incoming = free space
    print fsinfo.f_bavail * k_per_block
    # outgoing = used space screws up the scaling...oh well
    #print (fsinfo.f_blocks - fsinfo.f_bavail) * k_per_block
    print 0
    # uptime of target, what would that mean for df
    # name of target
