#!/usr/bin/env ruby

# parses the output of "ssh arx2 show global-config" to map nitrogen
# filesystems to underlying hosts & paths

volume, resources = nil, []

table   = {}
dupes = {}

ARGF.each { |line|
   case line
   when /^\s*volume\s+(\S+)/
      table[volume] = resources if volume
      volume, resources = $1, []
   when /^\s*filer\s+(\S+)/
      resources << $1 + '_io'
   when /^\s*export\s+\S+\s+(\S+)\s+as\s+(\S+)\s+/
      dupes[$2] = $1
   end
}

dupes.each { |dup, target|
  table[dup] = table[target] if table[target]
}

table.each { |volume, resources|
  puts "#{volume} #{resources.sort.uniq.join(' ')}" 
}
