#!/usr/bin/env ruby

# parses the output of "ssh arx2 show global-config" to map nitrogen
# filesystems to underlying hosts & paths

volume, resources = nil, []

table   = {}
dupes = {}

ARGF.each { |line|
   case line
   when %r{^\s*volume\s+(/\S+)}
      table[volume] = resources if volume
      volume, resources = $1, []
   when %r{^\s*filer\s+(\S+)}
      resources << $1 + '_io'
   when %r{^\s*export\s+\S+\s+(/\S+)\s+as\s+(/\S+)\s+}
      dupes[$2] = $1
   end
}

dupes.each { |dup, target|
  until target.empty? or table[target]
    target = target.split('/')[0..-2].join('/')
  end
  table[dup] = table[target] unless target.empty?
}

table.each { |volume, resources|
  puts "#{volume} #{resources.sort.uniq.join(' ')}" 
}
