#!/bin/bash

OIFS=$IFS
IFS=','

if [ $# -lt "$ARG_NO" ]; then
        echo 1>&2 $USAGE
        exit $E_USAGE
fi

HOSTS=$1
shift
CMD=""

while [ $# -ge 1 ]; do
        CMD="$CMD $1"
        shift
done

#meh.  The next eight lines (not including WS) are a standard construct in MoniaScript, it seems worthwhile to keep around.
USAGE="Usage: $(basename $0) \$HOSTS \$CMD"
ARG_NO=2
E_OK=0       # successful termination
E_USAGE=64      # command line usage error


for HOST in $HOSTS; do 
	ssh -n $HOST $CMD &> /tmp/$HOST.log & done
wait
IFS=$OIFS

exit $E_OK
