#!/bin/sh
# Exercise dotkit.  You need to "cd $DK_ROOT/etc/test" to run this.

#trap '/bin/rm -f ./new/*' 0 1 2
DK_ROOT=$PWD; export DK_ROOT

# Look up an absolute pathname for $1.
whereis()
{
  for d in /bin /usr/bin /sbin /usr/sbin /usr/local/bin
  do test -x $d/$1 && { echo $d/$1; return 0; }
  done
  return 1
}

# Strip trailing newline from echo.
echon() { echo "$@" | tr -d '\012'; }

# $1=testname, $2=shell
compare()
{
  if test -f ref/$1.ksh; then
    diff ref/$1.ksh new/$1.$2 > dif/$1.$2 && echon "ok ($2) " ||
      { echo "$2: Differences noted:  See dif/$1.$2.)"; return 1; }
  else
    echo "(Created reference output for $1)"
    mv new/$1.ksh ref/$1.ksh
  fi
}

# $1=SOURCE, $2=shell, $3=flags, $4=testname
test2()
{
  SHELL=`whereis $2`; export SHELL
  echo "Test: $4"
  env -i DK_ROOT=. DK_NODE=./Site=test _dk_inuse= \
           PATH=/bin:/usr/bin HOME= SHELL=$SHELL SYS_TYPE=foobar \
           USER=${USER:-$LOGNAME} \
           $SHELL $3 'eval `./init`'" && $1 ./$4"
  echo "###"
}

# $1=testname
test1()
{
  test2 . ksh -c $1 > new/$2.ksh
  test2 . bash -c $1 > new/$2.bash
  test2 source csh -fc $1 > new/$2.csh
  test2 source tcsh -fc $1 > new/$2.tcsh
}


######################################################################
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
export PATH

tests=${1:-*.t}
for t in $tests; do
  n=`basename $t .t`
  test1 $t $n
  echon "$n: "
  for s in ksh bash csh tcsh
  do
    compare $n $s
  done
  echo ""
done
